module.exports.ErrorMessage = {
  FIELD_IS_REQUIRED: 'FIELD_IS_REQUIRED',
  FIELD_INVALID: 'FIELD_INVALID',
  USERNAME_OR_PASSWORD_INCORRECT: 'USERNAME_OR_PASSWORD_INCORRECT',
  FIELD_VALUE_ALREADY_EXISTED: 'FIELD_VALUE_ALREADY_EXISTED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  UNAUTHORIZATION: 'UNAUTHORIZATION',
  NOT_FOUND: 'NOT_FOUND',
  NO_THING_TO_UPDATE: 'NO_THING_TO_UPDATE',
};
