module.exports.ErrorMessage = {
  FIELD_IS_REQUIRED: 'FIELD_IS_REQUIRED',
  FIELD_INVALID: 'FIELD_INVALID',
  USERNAME_OR_PASSWORD_INCORRECT: 'USERNAME_OR_PASSWORD_INCORRECT',
  INVALID_TOKEN: 'INVALID_TOKEN',
  UNAUTHORIZATION: 'UNAUTHORIZATION',
  NOT_FOUND: 'NOT_FOUND',
  NO_THING_TO_UPDATE: 'NO_THING_TO_UPDATE',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_NUMBER_ALREADY_EXISTS: 'PHONE_NUMBER_ALREADY_EXISTS',
  NO_THING_TO_UPLOAD: 'NO_THING_TO_UPLOAD',
};
