// mongodb
const MONGO_HOST = process.env.MONGO_HOST;
const MONGO_PORT = process.env.MONGO_PORT;
const MONGO_DATABASE_NAME = process.env.MONGO_DATABASE_NAME;
const MONGO_DATABASE_USERNAME = process.env.MONGO_DATABASE_USERNAME;
const MONGO_DATABASE_PASSWORD = process.env.MONGO_DATABASE_PASSWORD;
const MONGO_URL =
  MONGO_DATABASE_USERNAME && MONGO_DATABASE_PASSWORD
    ? `mongodb://${MONGO_DATABASE_USERNAME}:${MONGO_DATABASE_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE_NAME}?retryWrites=true`
    : `mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE_NAME}?retryWrites=true`;

const CONFIG = {
  ENV: process.env.ENV,
  HOST: process.env.HOST,
  PORT: process.env.PORT,

  // mongodb
  MONGO_HOST,
  MONGO_PORT,
  MONGO_DATABASE_NAME,
  MONGO_DATABASE_USERNAME,
  MONGO_DATABASE_PASSWORD,
  MONGO_URL,

  // jwt
  JWT_EXPIRATION: parseInt(process.env.JWT_EXPIRATION), // 86400 = 1 day
  JWT_SECRET: process.env.JWT_SECRET,
};

module.exports = CONFIG;
