const ErrorCode = {
  INVALID_PARAMS: 'INVALID_PARAMS',
  FIELD_CANNOT_BE_BLANK: 'FIELD_CANNOT_BE_BLANK',
  INVALID_TOKEN: 'INVALID_TOKEN',
  NOTHING_TO_UPDATE: 'NOTHING_TO_UPDATE',
  NOT_FOUND: 'NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_NUMBER_ALREADY_EXISTS: 'PHONE_NUMBER_ALREADY_EXISTS',
  USERNAME_OR_PASSWORD_INCORRECT: 'USERNAME_OR_PASSWORD_INCORRECT',
  UNAUTHORIZATION: 'UNAUTHORIZATION',
  EMAIL_OR_PHONE_NUMBER_IS_REQUIRED: 'EMAIL_OR_PHONE_NUMBER_IS_REQUIRED',
  FIELD_IS_REQUIRED: 'FIELD_IS_REQUIRED',
  FIELD_INVALID: 'FIELD_INVALID',
};

module.exports = ErrorCode;
