const ErrorCode = {
  FIELD_IS_REQUIRED: "FIELD_IS_REQUIRED",
  FIELD_INVALID: "FIELD_INVALID",
  EMAIL_OR_PASSWORD_INCORRECT: "EMAIL_OR_PASSWORD_INCORRECT",
  INVALID_TOKEN: "INVALID_TOKEN",
  UNAUTHORIZATION: "UNAUTHORIZATION",
  EMAIL_EXISTS: "EMAIL_EXISTS",
};

const ErrorMessage = {
  [ErrorCode.FIELD_IS_REQUIRED]: "FIELD_IS_REQUIRED",
  [ErrorCode.FIELD_INVALID]: "FIELD_INVALID",
  [ErrorCode.EMAIL_OR_PASSWORD_INCORRECT]: "EMAIL_OR_PASSWORD_INCORRECT",
  [ErrorCode.INVALID_TOKEN]: "INVALID_TOKEN",
  [ErrorCode.UNAUTHORIZATION]: "UNAUTHORIZATION",
  [ErrorCode.EMAIL_EXISTS]: "EMAIL_EXISTS",
};

module.exports = {
  ErrorCode,
  ErrorMessage,
};
